[tool.poetry]
name = "todo-list-in-python"
version = "0.1.0"
description = ""
authors = ["Shyden McM <sasteberis@hotmail.co.uk>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
